apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitea-listener-sa
  namespace: tekton-pipelines
secrets:
- name: gitea-secret
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: trgiggers-example-eventlistener-binding
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: gitea-listener-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-roles
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: triggers-example-eventlistener-clusterbinding
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: gitea-listener-sa
  namespace: tekton-pipelines
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-eventlistener-clusterroles
