apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cpu-usage-test
  namespace: monitoring
spec:
  groups:
  - name: cpu.rules
    rules:
    - alert: HighCPUUsage
      expr: (100 - (avg by (instance)(rate(node_cpu_seconds_total{mode="idle"}[2m])) * 100)) > 10
      for: 1m
      labels:
        severity: warning
      annotations:
        summary: "CPU usage high"
        description: "CPU usage > 10% for 1 minute on instance {{ $labels.instance }}"

