apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2025-09-11T13:04:23Z"
  generation: 6
  labels:
    app: traffic
  name: traffic
  namespace: traffic-receiver
  resourceVersion: "9448"
  uid: c1620c76-7f80-4868-8cbc-81880dd52553
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: traffic
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: traffic
    spec:
      containers:
      - image: docker.io/library/nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources:
          limits:
            cpu: 200m
          requests:
            cpu: 100m
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/log/nginx
          name: logs
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: logs
        persistentVolumeClaim:
          claimName: nginx-logs-pvc
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-09-11T13:04:23Z"
    lastUpdateTime: "2025-09-11T13:06:55Z"
    message: ReplicaSet "traffic-85ccdc6974" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2025-09-11T13:49:18Z"
    lastUpdateTime: "2025-09-11T13:49:18Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 6
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
