FROM debian:bookworm-slim

RUN apt update && \
    apt install -y curl gnupg bash && \
    rm -rf /var/lib/apt/lists/*

RUN curl -s 'https://install.zerotier.com/' | bash

RUN mkdir -p /var/lib/zerotier-one

ENTRYPOINT ["/bin/bash", "-c"]

CMD ["/usr/sbin/zerotier-one -d && \
      sleep 5 && \
      /usr/sbin/zerotier-cli join 4753cf475f4ceb2b && \
      exec tail -f /dev/null"]
